
# Site settings
locale: "ru-RU"
title: "CARAMELICA"
email: "mail@caramelica.info"
description: >- # this means to ignore newlines until "baseurl:"
  Новинка - карамель леденцовая "CARAMELICA"
minimal_mistakes_skin: air # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "ИП Бакликова Оксана Олеговна"
  avatar : "/assets/images/bio-photo_200_200.png"
  bio    : "Карамель приготовлена на основе натуральных ингредиентов, без добавления химических  красителей, ароматизаторов и консервантов."
  links:
    - label: "Email"
      icon: "fab fa-fw fa-github"
      url: "mailto:mail@caramelica.info"
    - label: "WWW"
      icon: "fas fa-fw fa-link"
      url: "https://caramelica.info/"
    - label: "VK"
      icon: "fab fa-fw fa-vk"
      url: "https://vk.com/ecaramelica"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/caramelica"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ecaramelica/"

footer:
  links:
    - label: "Email"
      icon: "fab fa-fw fa-github"
      url: "mailto:mail@caramelica.info"
    - label: "WWW"
      icon: "fas fa-fw fa-link"
      url: "https://caramelica.info/"
    - label: "VK"
      icon: "fab fa-fw fa-vk"
      url: "https://vk.com/ecaramelica"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/caramelica"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ecaramelica/"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
